#自动运行
name: Auto Api

on:
  push:
    branches:
      - master
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install requests
      run: |
        pip install requests
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/wangziyingwen/Autoapi.git /opt/Autoapi	
    - name: Test Api 
      run: |
        cd /opt/Autoapi
        python 1.py
