#自动调用api保活
name: Auto Api

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: 0 */12 * * *
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests
      run: |
        pip install requests
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/wangziyingwen/Autoapi.git /opt/Autoapi	
    - name: Test Api 
      run: |
        cd /opt/Autoapi
        python 1.py
